### PR TITLE
Wine specific codecs only

### PR DESCRIPTION
**Pull request by Gcenx**
Opened as a PR to help track changes.

<br>

### List of Ports being worked on
- [x] orc _(may need tweaks)_
- [x] gstreamer _(may need tweaks)_
- [x] gst-plugins-base _(may need tweaks)_
- [x] gst-plugins-good _(may need tweaks)_
- [x] gst-plugins-ugly _(may need tweaks)_
- [x] libmpeg2 (imported to avoid +x11 +sdl)
- [x] gst-libav
- [x] FFmpeg _(may need tweaks)_
- [ ] gst-plugins-bad

### CODE REVIEW

**Comment by zfigura** [comment]
Apologies if I'm reviewing a WIP, but I happened to look over this and notice that -good disables deinterlace, which Wine actually needs. I also noticed that "adder" seems to be misspelled in -base.

**Comment by Gcenx** [comment]
That’s more than fine I was actually planning to reach out to you about this anyway.

The disables were taken from Proton-GE in an attempt to speed up the process.

### gst-plugins-good
That can be enabled if you se anything else that’s disabled that needs to be enabled just let me know.

### gst-plugins-base
Could have swore that option was fixed already. Is there anything else I should enable for this? , as there wasn’t anything mentioned for this in the notes you provided Gijs.

**Comment by zfigura** [comment]
Yeah, sorry, Gijs asked me about codecs and I didn't think to list non-codecs. The full list of non-codecs we should need are:

base: audioconvert, decodebin (from playback), typefind (dependency of decodebin), videoconvert
good: deinterlace, videoflip (from videofilter)

As before I'm not perfectly confident that's everything we need. It's also worth pointing out that there are some we don't need now but I could easily anticipate needing in the future:

base: appsink, appsrc?, audioresample, videoscale, videorate
good: videobox?, videocrop

I would probably recommend compiling everything that's not in ext/ or sys/, or at least everything that isn't a codec. In theory that should be uncontroversial. But then again I don't know about what internal discussion there has been.

**Comment by Gcenx** [comment]
So it's better to just enabled everything in the "Feature options for plugins with no external deps" section?

The issue we've found was things under "Feature options for plugins with external deps" as macports loves to pull in things like X11/Mesa for no reason, so anything that gets built stupidly needs to be pulled in and modified. Also need to avoid anything that compiles using RUST as they dropped i386 for macOS and macports never implemented cross-compiling RUST for i386 within it's Port.

**Comment by zfigura** [comment]
> So it's better to just enabled everything in the "Feature options for plugins with no external deps" section?

I at least can't anticipate any harm in it...

Especially for -good and -base.

> The issue we've found was things under "Feature options for plugins with external deps" as macports loves to pull in things like X11/Mesa for no reason, so anything that gets built stupidly needs to be pulled in and modified. Also need to avoid anything that compiles using RUST as they dropped i386 for macOS and macports never implemented cross-compiling RUST for i386 within it's Port.

Yeah, that tracks. Wine shouldn't need anything like that (no gpu sinks or sources or anything). We do want a couple of decoders that use external libraries (libav of course, but also libmpg123, and *maybe* also libopenh264?) but that should be it.

Is there any Rust code to worry about? I see there's a gst-plugins-rs repository, which is probably an attempt to Rewrite Everything, but I didn't immediately see Rust code in the main repositories...

**Comment by Gcenx** [comment]
The library to worry about would be `librsvg`, currently that's force downgraded to a pre-cargo version to avoid rust.

**Comment by Gcenx** [comment]
Strange `libmpeg2` does provide `mpeg2dec` binary even without sdl yet homebrew and most Linux distros list that as required?

**Comment by zfigura** [comment]
Just from skimming, it appears that mpeg2dec provides a way to output video to the screen, and it offers SDL as one backend for this if it's available at compile time.

**Comment by zfigura** [comment]
Obviously we don't need this capability, or the mpeg2dec binary at all, for Wine.

**Comment by Gcenx** [comment]
Still not decided how to best handle ffmpeg for gst-libav but the current implementation using the ffmpeg-meson port as a subproject.

Could you let me know what options need to be enabled/disabled, I’ve copied the meson_options.txt directly into the Portfile.

**Comment by zfigura** [comment]
I haven't read the meson files, but judging from the configure script, the external dependencies that *might* be necessary are bzlib, zlib, lzma. Everything else either relates to I/O, or is disabled by default.

**Comment by Gcenx** [comment]
Here's a build log [gst-libav.log.zip](https://github.com/Gcenx/macports-gstreamer1/files/7414265/gst-libav.log.zip)

> ## gst-libav
> mpegvideo, mpeg2video, h264, h265, av1, wmv1, wmv2, wmv3, mp1float, mp2float, mpeg4, cinepak, aac, wmav1, wmav2, wmapro, wmavoice 

As gst-libav is just a wrapper for ffmpeg I'm assuming I need to enabled the above from what you've said prior.

**Comment by zfigura** [comment]
Sorry, I'm not sure what you want me to be looking for from the build log?

**Comment by Gcenx** [comment]
I'd added it in case you needed a reference for what it's looking for at while compiling as the meson files are not great as there generated via script.

As gst-libav doesn't mention any plugins so I'm assuming additional options need to be enabled within ffmpeg to cover those.

**Comment by zfigura** [comment]
Right, gst-libav just exposes what's available in libav. I believe it does so at runtime rather than at compile time.

**Comment by Gcenx** [comment]
`FFmpeg` & `gst-libav` we’re pushed, some fixes I carry we’re merged into Macports-ports.

Now to work on `gst-plugins-bad`

**Comment by Gcenx** [comment]
Closing since we’ve been directly using this branch for a while now, I’ll open another PR for a clean file later.

**Pull request closed without merging**
